# Copyright (C) 2011-2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/togari/setup-makefiles.sh
PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/togari

PRODUCT_COPY_FILES += \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Bluetooth_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_General_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Global_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Handset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Hdmi_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Headset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Fluid/Fluid_Speaker_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Bluetooth_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_General_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Global_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Handset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Hdmi_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Headset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Liquid/Liquid_Speaker_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/sony/togari/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_chip_id_0x74_config_id_0x0011.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_chip_id_0x74_config_id_0x0460.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_chip_id_0x75_config_id_0x0010.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_chip_id_0x75_config_id_0x0012.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_chip_id_0x75_config_id_0x0013.bin \
    vendor/sony/togari/proprietary/etc/firmware/touch_module_id_0x43.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x43.img \
    vendor/sony/togari/proprietary/etc/firmware/touch_module_id_0x44.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/touch_module_id_0x44.img \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b00 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b01 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b02 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b03 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b04 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b05 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b06:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b06 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b07:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b07 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b08:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b08 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b09:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b09 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b10:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b10 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.b11:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.b11 \
    vendor/sony/togari/proprietary/etc/firmware/adsp.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/adsp.mdt \
    vendor/sony/togari/proprietary/etc/firmware/mba.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mba.b00 \
    vendor/sony/togari/proprietary/etc/firmware/mba.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mba.mdt \
    vendor/sony/togari/proprietary/etc/firmware/modem.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b00 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b01 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b02 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b03 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b04 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b05:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b05 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b08:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b08 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b11:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b11 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b13:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b13 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b14:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b14 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b15:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b15 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b16:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b16 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b17:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b17 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b18:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b18 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b19:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b19 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b20:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b20 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b21:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b21 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b22:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b22 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b25:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b25 \
    vendor/sony/togari/proprietary/etc/firmware/modem.b26:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.b26 \
    vendor/sony/togari/proprietary/etc/firmware/modem.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/modem.mdt \
    vendor/sony/togari/proprietary/etc/firmware/tzhdcp.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzhdcp.b00 \
    vendor/sony/togari/proprietary/etc/firmware/tzhdcp.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzhdcp.b01 \
    vendor/sony/togari/proprietary/etc/firmware/tzhdcp.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzhdcp.b02 \
    vendor/sony/togari/proprietary/etc/firmware/tzhdcp.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzhdcp.b03 \
    vendor/sony/togari/proprietary/etc/firmware/tzhdcp.flist:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzhdcp.flist \
    vendor/sony/togari/proprietary/etc/firmware/tzhdcp.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tzhdcp.mdt \
    vendor/sony/togari/proprietary/etc/sensors_calib.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors_calib.conf \
    vendor/sony/togari/proprietary/lib/libcald_hal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libcald_hal.so \
    vendor/sony/togari/proprietary/usr/idc/clearpad.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/clearpad.idc \
    vendor/sony/togari/proprietary/usr/idc/max1187x_pen_0.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/max1187x_pen_0.idc \
    vendor/sony/togari/proprietary/usr/idc/max1187x_touchscreen_0.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/max1187x_touchscreen_0.idc \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/cam_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/cam_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/cap_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/cap_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/chokoball.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/chokoball.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/color_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/dataflow.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/debug_mgr.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/exposure_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/face_detector.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/flicker_detector.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/focus_stats_conv.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/hal_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/hal_ctrl_platform.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/hdr_comp.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/idt_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/image_conv.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/imgproc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/imgproc.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/jpeg_enc.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/lens_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/module.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/module.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/motion_estimation.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/multiframe_nr.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/object_tracker.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/scene_detector.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/snapshot_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SEM08BS2/streaming_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM08BS2/streaming_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2_BU64291GWZ.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2_BU64291GWZ.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/cam_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/cam_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/cap_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/cap_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/chokoball.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/chokoball.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/color_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/dataflow.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/debug_mgr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/debug_mgr.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/exposure_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/face_detector.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/flicker_detector.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/focus_stats_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/focus_stats_conv.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/hal_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/hal_ctrl_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/hal_ctrl_platform.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/hdr_comp.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/idt_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/image_conv.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/imgproc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/imgproc.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2_IMX134.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2_IMX134.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/jpeg_enc.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/jpeg_enc.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/lens_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/module.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/module.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/motion_estimation.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/multiframe_nr.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/multiframe_nr.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/object_tracker.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/scene_detector.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/snapshot_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/snapshot_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/SOI08BS2/streaming_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SOI08BS2/streaming_ctrl.dat \
    vendor/sony/togari/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/togari/proprietary/vendor/camera/product.dat:$(TARGET_COPY_OUT_VENDOR)/camera/product.dat \
    vendor/sony/togari/proprietary/vendor/camera/product_CACAO.dat:$(TARGET_COPY_OUT_VENDOR)/camera/product_CACAO.dat \
    vendor/sony/togari/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/sony/togari/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/sony/togari/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/sony/togari/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/sony/togari/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/sony/togari/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/sony/togari/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/sony/togari/proprietary/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    vendor/sony/togari/proprietary/etc/firmware/c6x02/Android:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/c6x02/Android
